### ISSUE TITLE
it is broken

### ISSUE THREAD

**Issue by igeo** [bloodlee/flickr_serverip_getter#1]
parsing, please stand by...
/usr/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 58 of the file src/flickr_serverip_getter.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Traceback (most recent call last):
  File "src/flickr_serverip_getter.py", line 72, in <module>
    global_server = getServerName(global_server_status_icon_url)
  File "src/flickr_serverip_getter.py", line 43, in getServerName
    return m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by bloodlee** [comment]
Fixed! Flickr is using HTTPS now.
Please sync and try again.

**Comment by igeo** [comment]
worked. rocks!
